// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASRGn1lBDm9sIhvLLZtmEXOvTwSHa_5zo',
    appId: '1:630594473617:web:dc30a4a983a63c6df57930',
    messagingSenderId: '630594473617',
    projectId: 'parivarmilap',
    authDomain: 'parivarmilap.firebaseapp.com',
    storageBucket: 'parivarmilap.firebasestorage.app',
    measurementId: 'G-ELNMMPQPV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgdGFCx_ZCSwGDzyNkcw12IgJBOn8-SI',
    appId: '1:630594473617:android:272b0bae273b919ff57930',
    messagingSenderId: '630594473617',
    projectId: 'parivarmilap',
    storageBucket: 'parivarmilap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUB0wlx9WgzlbFikAuVABhlejxGEeFjI',
    appId: '1:630594473617:ios:0997a53a2bf748eef57930',
    messagingSenderId: '630594473617',
    projectId: 'parivarmilap',
    storageBucket: 'parivarmilap.firebasestorage.app',
    iosBundleId: 'com.example.webAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNUB0wlx9WgzlbFikAuVABhlejxGEeFjI',
    appId: '1:630594473617:ios:0997a53a2bf748eef57930',
    messagingSenderId: '630594473617',
    projectId: 'parivarmilap',
    storageBucket: 'parivarmilap.firebasestorage.app',
    iosBundleId: 'com.example.webAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASRGn1lBDm9sIhvLLZtmEXOvTwSHa_5zo',
    appId: '1:630594473617:web:2cbfd08b2bc9b19af57930',
    messagingSenderId: '630594473617',
    projectId: 'parivarmilap',
    authDomain: 'parivarmilap.firebaseapp.com',
    storageBucket: 'parivarmilap.firebasestorage.app',
    measurementId: 'G-HV5XMGQHE0',
  );
}
