// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xGrykr0gj2CtlRMOWtnl_I15BMvokX8',
    appId: '1:666802123103:web:48d7cb8e5bdbc2f055c6ea',
    messagingSenderId: '666802123103',
    projectId: 'webapp-a487f',
    authDomain: 'webapp-a487f.firebaseapp.com',
    storageBucket: 'webapp-a487f.firebasestorage.app',
    measurementId: 'G-3W5MHDCYQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtprbHmrhgOj76x59zg6B1FvO54-suRuk',
    appId: '1:666802123103:android:0ff92991c0bce7c055c6ea',
    messagingSenderId: '666802123103',
    projectId: 'webapp-a487f',
    storageBucket: 'webapp-a487f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeq4bF0PrMLKAU1rhs2bkB1yknbJyL3Xw',
    appId: '1:666802123103:ios:dc5b4a958778d48f55c6ea',
    messagingSenderId: '666802123103',
    projectId: 'webapp-a487f',
    storageBucket: 'webapp-a487f.firebasestorage.app',
    iosBundleId: 'com.example.webAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeq4bF0PrMLKAU1rhs2bkB1yknbJyL3Xw',
    appId: '1:666802123103:ios:dc5b4a958778d48f55c6ea',
    messagingSenderId: '666802123103',
    projectId: 'webapp-a487f',
    storageBucket: 'webapp-a487f.firebasestorage.app',
    iosBundleId: 'com.example.webAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5xGrykr0gj2CtlRMOWtnl_I15BMvokX8',
    appId: '1:666802123103:web:48d7cb8e5bdbc2f055c6ea',
    messagingSenderId: '666802123103',
    projectId: 'webapp-a487f',
    authDomain: 'webapp-a487f.firebaseapp.com',
    storageBucket: 'webapp-a487f.firebasestorage.app',
    measurementId: 'G-3W5MHDCYQQ',
  );

}